# Generated by Django 4.2.3 on 2023-09-14 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetsDeployed",
            fields=[
                ("region", models.CharField(max_length=50)),
                ("floor", models.CharField(max_length=20)),
                ("asset_type", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("Working", "Working"), ("Faulty", "Faulty")],
                        max_length=30,
                    ),
                ),
                ("monitor_model", models.CharField(max_length=50)),
                ("monitor_serial_number", models.CharField(max_length=50)),
                ("asset_model", models.CharField(max_length=50)),
                ("asset_model_number", models.CharField(max_length=50)),
                (
                    "asset_serial_number",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="asset.department",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="asset.staff"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="asset.section"
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="asset.station",
                    ),
                ),
            ],
        ),
    ]
